# Generated by Django 3.1.4 on 2021-01-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20210119_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='duration',
            field=models.PositiveSmallIntegerField(verbose_name='Время приготовления'),
        ),
    ]
